# Generated by Django 5.0.4 on 2024-04-15 09:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WEBSITE", "0002_pagecontent_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="uploads/pages/%Y/%m/%d/"
            ),
            preserve_default=False,
        ),
    ]
