# Generated by Django 5.0.4 on 2024-04-19 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WEBSITE", "0003_pagecontent_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="Created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
