# Generated by Django 5.0.4 on 2024-04-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WEBSITE", "0006_alter_contactinfo_facebook_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="Facebook_link",
            field=models.URLField(default="www.facebook.com"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="Instagram_link",
            field=models.URLField(default="www.instagram.com"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="Linkedin_link",
            field=models.URLField(default="www.linkedin.com"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="X_link",
            field=models.URLField(default="www.twitter.com"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="Youtube_link",
            field=models.URLField(default="www.youtube.com"),
        ),
    ]
