# Generated by Django 5.0.4 on 2024-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WEBSITE", "0007_alter_contactinfo_facebook_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="Address",
            field=models.CharField(max_length=255),
        ),
    ]
