# Generated by Django 5.0.4 on 2024-04-15 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PRODUCTS_SERVICES", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ICON",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to="uploads/products/%Y/%m/%d/",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="SHORT_DESCRIPTION",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="services",
            name="ICON",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to="uploads/services/%Y/%m/%d/",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="services",
            name="IMAGE",
            field=models.ImageField(
                default=django.utils.timezone.now,
                upload_to="uploads/services/%Y/%m/%d/",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="services",
            name="SHORT_DESCRIPTION",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
