# Generated by Django 5.0.4 on 2024-04-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VACANCIES", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
