# Generated by Django 5.0.4 on 2024-04-19 05:59

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VACANCIES", "0003_jobs_about_role_jobs_job_requirement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="Job_name",
        ),
        migrations.AddField(
            model_name="jobs",
            name="Job_Type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "FULL_TIME"),
                    ("REMOTE", "REMOTE"),
                    ("HYBRID", "HYBRID"),
                    ("PARTIME", "PARTIME"),
                ],
                default=django.utils.timezone.now,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobs",
            name="About_Role",
            field=ckeditor.fields.RichTextField(default=""),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="Job_Requirement",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
