# Generated by Django 5.0.4 on 2024-04-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VACANCIES", "0004_remove_jobs_job_name_jobs_job_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidates",
            name="Phone",
            field=models.CharField(default="123", max_length=10),
        ),
    ]
