# Generated by Django 5.0.4 on 2024-04-19 08:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("VACANCIES", "0006_candidates_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="About_Role",
            field=django_ckeditor_5.fields.CKEditor5Field(default=""),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="Job_Requirement",
            field=django_ckeditor_5.fields.CKEditor5Field(default=""),
        ),
    ]
